version: '2'
services:
  ms04-app:
    image: ms04
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://ms04-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=ms04
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  ms04-mongodb:
    extends:
      file: mongodb.yml
      service: ms04-mongodb
